Set default HTTP timeouts
keboola/juicer pull request #41
Opened 2022-03-07 10:11 UTC by webrouse

Slack: https://keboola.slack.com/archives/C02C3GZUS/p1646478795041059
ZD: https://keboola.zendesk.com/agent/tickets/21533

2022-03-07 20:45 UTC, ondrajodas approved these changes

2022-03-07 20:45 UTC, ondrajodas commented on src/Client/RestClient.php
> +        $guzzleConfig['connect_timeout'] = $guzzleConfig['connect_timeout'] ?? 30;
lepší by to bylo přes nějaký konstanty

2022-03-08 07:12 UTC, ondrajodas requested changes

2022-03-08 07:12 UTC, ondrajodas commented on src/Client/RestClient.php
> +        $guzzleConfig['timeout'] = $guzzleConfig['connect_timeout'] ?? self::DEFAULT_REQUEST_TIMEOUT;
!!! teď jsem si všiml, tady má být :
```
$guzzleConfig['timeout'] = $guzzleConfig['timeout'] ?? self::DEFAULT_REQUEST_TIMEOUT;
```

2022-03-08 07:29 UTC, webrouse commented on src/Client/RestClient.php
> +        $guzzleConfig['timeout'] = $guzzleConfig['connect_timeout'] ?? self::DEFAULT_REQUEST_TIMEOUT;
dik

2022-03-08 08:03 UTC, ondrajodas approved these changes

2022-03-08 08:08 UTC, merged